language: scala

scala:
  - "2.11.8"
  - "2.12.1"

jdk:
  - oraclejdk8

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  matrix:
    - CMD="cd akka-sample-camel-java && sbt ++$TRAVIS_SCALA_VERSION test"
    - CMD="cd akka-sample-camel-scala && sbt ++$TRAVIS_SCALA_VERSION test"
    - CMD="cd akka-sample-cluster-java && sbt ++$TRAVIS_SCALA_VERSION multi-jvm/test"
    - CMD="cd akka-sample-cluster-scala && sbt ++$TRAVIS_SCALA_VERSION multi-jvm/test"
    - CMD="cd akka-sample-main-java && sbt ++$TRAVIS_SCALA_VERSION test"
    - CMD="cd akka-sample-main-java && mvn test -P $TRAVIS_SCALA_VERSION"
    - CMD="cd akka-sample-main-scala && sbt ++$TRAVIS_SCALA_VERSION test"

script:
  - eval "$CMD"
